version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo1
      - mongo2
    ports:
      - "3001:3001"

  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - backend-network

  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - backend-network

networks:
  backend-network:
